# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjNMN0yh024uJH3sWmgNGM0zewirsT6s
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# 1. تحميل البيانات
df = pd.read_csv("Human_Gene_Data_Analysis_1000_Records.csv")

# 2. تحديد الميزات (Features) والهدف (Target)
features = [
    "Expression_Level",
    "Expression_Log2",
    "Fold_Change",
    "Significance_PValue",
]
X = df[features]
y = df["Condition"]

# 3. تقسيم البيانات إلى مجموعتي تدريب (80%) واختبار (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. تدريب النموذج
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. التنبؤ وتقييم الأداء
y_pred = model.predict(X_test)
print("Daqat Al-Nomoozag (Accuracy):", accuracy_score(y_test, y_pred))
print("\nTaqreer Al-Adaa:\n", classification_report(y_test, y_pred))

import numpy as np
import pandas as pd
import streamlit as st
from sklearn.ensemble import RandomForestClassifier

st.set_page_config(page_title="تطبيق التنبؤ بالجينات", layout="centered")

st.title("🧬 تطبيق التنبؤ بالحالة الجينية")
st.write(
    "قم بإدخال بيانات التعبير الجيني للتنبؤ بالحالة (Control أو Treatment)"
)


@st.cache_data
def load_and_train_model():
    df = pd.read_csv("Human_Gene_Data_Analysis_1000_Records.csv")
    features = [
        "Expression_Level",
        "Expression_Log2",
        "Fold_Change",
        "Significance_PValue",
    ]
    X = df[features]
    y = df["Condition"]

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model


model = load_and_train_model()

st.sidebar.header("مدخلات الجين")
expression_level = st.sidebar.number_input(
    "Expression Level", value=500.0, step=10.0
)
expression_log2 = st.sidebar.number_input(
    "Expression Log2", value=8.0, step=0.1
)
fold_change = st.sidebar.number_input("Fold Change", value=1.5, step=0.1)
p_value = st.sidebar.number_input(
    "Significance P-Value", value=0.01, step=0.001, format="%.6f"
)

if st.button("تنبؤ"):
    input_data = pd.DataFrame(
        [[expression_level, expression_log2, fold_change, p_value]],
        columns=[
            "Expression_Level",
            "Expression_Log2",
            "Fold_Change",
            "Significance_PValue",
        ],
    )
    prediction = model.predict(input_data)[0]
    proba = model.predict_proba(input_data)[0]

    st.success(f"النتيجة المتوقعة: **{prediction}**")
    st.write(f"نسبة الثقة: **{np.max(proba)*100:.2f}%**")